import './globals.css'

import React, { Suspense } from 'react';

import SearchBar from '@/components/SearchBar'

export const metadata = {
  title: 'Sailoogle',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="data:,"></link>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body>
        <Suspense>
          <SearchBar></SearchBar>
          {children}
        </Suspense>
      </body>
    </html>
  )
}